### ISSUE TITLE
Add issue & PR templates for submission service

### ISSUE THREAD

**Issue by danyloid** [flam-flam/submission-service#13]
#### Acceptance
- Add default PR template for the `submission-service` repo
- Add default issue template for the `submission-service` repo

#### Additional context
- [GitHub Issue and PR templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates)
- [Creating PR template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)
- [Configuring issue templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser)

**Comment by timberhill** [comment]
I wonder if it makes sense to add one for the whole org? Here are the docs: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file

We already have the .github repo 👀
